version: "3"
services:
  api-server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node-sheffield-badminton
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local